driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  require_chef_omnibus: "12.22.5"

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list: test::default
  - name: compile_time
    run_list: test::default
    attributes:
      build-essential:
        compile_time: true
